extends Node

var language: String = "es"

var translations: Dictionary = {
	"es": {
		"game_title": "TANK OVERDRIVE",
		"game_subtitle": "AUTO-DEFENDER",
		"play": "JUGAR",
		"settings": "CONFIGURACIÓN",
		"records": "RECORDS",
		"settings_title": "CONFIGURACIÓN DE PARTIDA",
		"spawn_interval_title": "Intervalo de aparición",
		"spawn_interval_tooltip": "Menor intervalo significa apariciones más rápidas",
		"enemy_speed_title": "Velocidad de enemigos",
		"detection_title": "Área de reacción del tanque",
		"spawn_value": "%.2f s entre apariciones",
		"speed_value": "%.0f px/s",
		"detection_value": "%.0f px de radio",
		"sfx_title": "Volumen de efectos",
		"music_title": "Volumen de música",
		"volume_value": "%d%%",
		"apply": "APLICAR",
		"reset_defaults": "RESTABLECER VALORES",
		"back": "VOLVER",
		"records_title": "TABLA DE RECORDS",
		"no_records": "Aún no hay récords guardados.",
		"records_position": "POS",
		"records_name": "NOMBRE",
		"records_score": "PUNTAJE",
		"records_time": "TIEMPO",
		"records_defeated": "BAJAS",
		"records_credits": "CRED.",
		"records_level": "NIVEL",
		"tank_status": "ESTADO DEL TANQUE",
		"damage_zones": "Zonas de daño",
		"front": "Frontal",
		"rear": "Trasero",
		"left": "Izquierdo",
		"right": "Derecho",
		"turret": "Torreta",
		"ok": "OK",
		"damaged": "DAÑADA",
		"run": "PARTIDA",
		"shop": "TIENDA",
		"credits": "Créditos: %d",
		"cadence": "Cadencia: %.2f s  |  %.2f disparos/s",
		"movement": "Movimiento: %.0f px/s",
		"time": "Tiempo: %02d:%02d",
		"enemies": "Enemigos: %d / %d",
		"defeated": "Eliminados: %d",
		"difficulty_levels": "Spawn: nivel %d  |  Velocidad: nivel %d",
		"repair_front": "Rep. frontal",
		"repair_rear": "Rep. trasero",
		"repair_left": "Rep. izquierdo",
		"repair_right": "Rep. derecho",
		"repair_turret": "Rep. torreta",
		"upgrade_armor": "M. blindaje",
		"upgrade_fire_rate": "M. cadencia",
		"upgrade_turret_rotation": "M. giro torreta",
		"game_over": "GAME OVER",
		"score": "Puntaje",
		"score_time": "Tiempo",
		"score_enemies": "Enemigos",
		"score_credits": "Créditos",
		"difficulty": "Nivel",
		"new_record": "NUEVO RECORD",
		"player_name_placeholder": "Escribe tu nombre",
		"save_record": "GUARDAR RECORD",
		"record_saved": "RECORD GUARDADO",
		"return_home": "VOLVER AL INICIO",
	},
	"en": {
		"game_title": "TANK OVERDRIVE",
		"game_subtitle": "AUTO-DEFENDER",
		"play": "PLAY",
		"settings": "SETTINGS",
		"records": "LEADERBOARD",
		"settings_title": "GAME SETTINGS",
		"spawn_interval_title": "Spawn interval",
		"spawn_interval_tooltip": "Lower interval means faster enemy spawns",
		"enemy_speed_title": "Enemy speed",
		"detection_title": "Tank reaction area",
		"spawn_value": "%.2f s between spawns",
		"speed_value": "%.0f px/s",
		"detection_value": "%.0f px radius",
		"sfx_title": "Effects volume",
		"music_title": "Music volume",
		"volume_value": "%d%%",
		"apply": "APPLY",
		"reset_defaults": "RESET DEFAULTS",
		"back": "BACK",
		"records_title": "LEADERBOARD",
		"no_records": "No records saved yet.",
		"records_position": "POS",
		"records_name": "NAME",
		"records_score": "SCORE",
		"records_time": "TIME",
		"records_defeated": "KILLS",
		"records_credits": "CRED.",
		"records_level": "LEVEL",
		"tank_status": "TANK STATUS",
		"damage_zones": "Damage zones",
		"front": "Front",
		"rear": "Rear",
		"left": "Left",
		"right": "Right",
		"turret": "Turret",
		"ok": "OK",
		"damaged": "DAMAGED",
		"run": "RUN",
		"shop": "SHOP",
		"credits": "Credits: %d",
		"cadence": "Rate: %.2f s  |  %.2f shots/s",
		"movement": "Movement: %.0f px/s",
		"time": "Time: %02d:%02d",
		"enemies": "Enemies: %d / %d",
		"defeated": "Defeated: %d",
		"difficulty_levels": "Spawn: level %d  |  Speed: level %d",
		"repair_front": "Rep. front",
		"repair_rear": "Rep. rear",
		"repair_left": "Rep. left",
		"repair_right": "Rep. right",
		"repair_turret": "Rep. turret",
		"upgrade_armor": "Upgrade armor",
		"upgrade_fire_rate": "Upgrade fire rate",
		"upgrade_turret_rotation": "Upgrade turret turn",
		"game_over": "GAME OVER",
		"score": "Score",
		"score_time": "Time",
		"score_enemies": "Enemies",
		"score_credits": "Credits",
		"difficulty": "Level",
		"new_record": "NEW RECORD",
		"player_name_placeholder": "Enter your name",
		"save_record": "SAVE RECORD",
		"record_saved": "RECORD SAVED",
		"return_home": "RETURN HOME",
	},
}

func text(key: String) -> String:
	var language_texts: Dictionary = translations.get(language, translations["es"])
	return language_texts.get(key, key)

func set_language(new_language: String) -> void:
	if translations.has(new_language):
		language = new_language
